extends Button
	
#CURRENT BUTTON FOR CLOSING THE PROJECT
func _on_pressed():
	get_tree().quit()
#CHANGE FUNCTIONALITY LATER SO THAT IT INSTEAD GENERATES A BOX PROMPTING WHETHER OR NOT THE PLAYER ACTUALLY WANTS TO EXIT
