extends Node

#VARIABLE TO LOCK SPEED OF THE TRAIN
var locomotionLock = false
#VARIABLE USED TO DETERMINE FRAMES OF THE PARALLAX BACKGROUNDS
var frame = 1
#VARIABLE DICTATING WHETHER OR NOT THE TUNNEL TRANSITION IS IN USE
var tunnelLock = false

func _ready():
	pass
#NEEDS CODE FOR CLICKTHROUGH SO WINDOWS VISIBLE BEHIND THE GAME MAY BE INTERACTED WITH
