extends Node

#VARIABLE USED TO DICTATE THE SPEED OF TRAIN ANIMATION, AS WELL AS THE SPEED OF THE PARALLAX LAYERS
var locomotion = .5
#VARIABLE USED TO DETERMINE FRAMES OF THE PARALLAX BACKGROUNDS
var frame = 1

func _ready():
	pass
#NEEDS CODE FOR CLICKTHROUGH SO WINDOWS VISIBLE BEHIND THE GAME MAY BE INTERACTED WITH
