extends ParallaxBackground

@onready var entrance = %entrance
@onready var exit = %exit

#FUNCTION TO START THE MOVEMENT OF THE TUNNEL ENTRANCE TOWARD THE TRAIN
func _ready() -> void:
	pass
	enterTunnel()
	
func enterTunnel():
	#BEGINS BY MATCHING SPEED OF THE TUNNEL ENTRANCE SPRITE WITH THE TRACKS
	entrance.motion_scale = Vector2(0.7, 0.7)
	#CREATE A TRIGGER THAT FIRES A SIGNAL WHEN THE SPRITE CROSSES THRESHOLD, RESETTING FOR NEXT TIME
	
func exitTunnel():
	#BEGINS BY MATCHING SPEED OF THE TUNNEL EXIT SPRITE WITH THE TRACKS
	exit.motion_scale = Vector2(0.7, 0.7)
	#USE TRIGGER TO FIRE SIGNAL WHEN SPRITE CROSSES THRESHOLD, RESETTING FOR NEXT TIME
