extends Node2D

#CREATE FUNCTIONALITY THAT ALLOWS CHOICES AT STOPS BUT LOCKS DURING TRIPS
#ACCURATELY SHOW PROGRESS OF THE TRAIN ALONG ROUTES
#MAKE CHANGES TO LANDSCAPE AT THE APPROPRIATE TIME ACCORDING TO THE MAP
#SEND THE RIGHT DETAILS TO THE STATION SPAWNER BASED ON THE DESTINATION
#MODULATE HOVERED CITY CHOICES DURING SELECTION
